#ifndef GENALGO_JSONSERIALIZER_FWD_HPP
#define GENALGO_JSONSERIALIZER_FWD_HPP

#include "base.hpp"

GA_NAMESPACE_BEGIN
class JSONSerializerState;
class JSONObjectBuilder;
class JSONArrayBuilder;
GA_NAMESPACE_END

#endif // GENALGO_JSONSERIALIZER_FWD_HPP
