#ifndef GENALGO_JSONDESERIALIZER_FWD_HPP
#define GENALGO_JSONDESERIALIZER_FWD_HPP

#include "base.hpp"

GA_NAMESPACE_BEGIN

class JSONDeserializerState;
class _JSONObjectConsumer;
class JSONArrayConsumer;

GA_NAMESPACE_END

#endif // GENALGO_JSONDESERIALIZER_FWD_HPP
